### ISSUE TITLE
second issue with mac os 

### ISSUE THREAD

**Issue by LukeRabauke** [ucczs/AoC_Preparator#1]
There is an issue in the template xxx.c file:

I am running into an endless loop with the following char variable definition:
char const* const fileName = ".\\input.txt";

The following fixed this issue for me:

-->

char const* const fileName = "input.txt";

<img width="1440" alt="Bildschirmfoto 2021-11-17 um 09 06 41" src="https://user-images.githubusercontent.com/76217146/142160375-c230a953-07fa-4c68-8d4e-c82012e1795b.png">

**Comment by ucczs** [comment]
The original solution was os specific. With commit [63a4189e](https://github.com/ucczs/AoC_Preparator/commit/63a4189e4e5509aceefedf023a88e0842ff29fa4) it should work now also on mac os.
